services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file:
      - .env
    environment:
      - REPCHESS_DB_PATH=/app/data/database.db
      - REPCHESS_LOG_DIR=/app/data/logs
      - TELEGRAM_API_BASE=http://telegram-bot-api:8081
    volumes:
      - ../data:/app/data 
      - ../telegram_bot_data:/bot_data
    depends_on:
      - telegram-bot-api

  telegram-bot-api:
    image: telegram-bot-api-local
    container_name: telegram-bot-api
    restart: unless-stopped
    env_file: 
    - .env
    command:
      - "--local"
      - "--dir=/bot_data"
    volumes:
      - ../telegram_bot_data:/bot_data
    ports:
      - "127.0.0.1:8081:8081"