# services:
#   bot:
#     image: cr.yandex/crpbcr0nc3rlukp8pajp/chessbot/bot:latest
#     build:
#       context: .
#       dockerfile: bot.Dockerfile
#     env_file:
#       - .env
#     environment:
#       - REPCHESS_DB_PATH=/data/database.db
#       - REPCHESS_LOG_DIR=/data
#       - TELEGRAM_API_BASE=http://telegram-bot-api:8081
#     volumes:
#       - ~/chessbot/bot:/data:rw
#     deploy:
#       update_config:
#         order: stop-first
#         failure_action: rollback

#   telegram-bot-api:
#     image: evilfreelancer/docker-telegram-bot-api:latest
#     restart: unless-stopped
#     env_file:
#       - .env
#     environment:
#       TELEGRAM_LOCAL: "true"
#       TELEGRAM_HTTP_PORT: 8081
#     volumes:
#       - ~/chessbot/telegram-bot-api:/var/lib/telegram-bot-api
#     ports:
#       - "8081:8081"

services:
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    env_file:
      - .env
    environment:
      - REPCHESS_DB_PATH=/app/data/database.db
      - REPCHESS_LOG_DIR=/app/data/logs
      - TELEGRAM_API_BASE=http://telegram-bot-api:8081
    volumes:
      - ../data:/app/data 
      - ../telegram_bot_data:/bot_data
    depends_on:
      - telegram-bot-api

  telegram-bot-api:
    image: telegram-bot-api-local
    container_name: telegram-bot-api
    restart: unless-stopped
    env_file: 
    - .env
    command:
      - "--local"
      - "--dir=/bot_data"
    volumes:
      - ../telegram_bot_data:/bot_data
    ports:
      - "127.0.0.1:8081:8081"