name: Deploy Telegram bot

on:
  push:
    branches:
      #- release
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - run: docker compose build

      - name: 'Create .env file'
        run: |
          touch .env
          echo 'REPCHESS_TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_TOKEN }}' >> .env

      - run: docker compose push

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}


      - name: Deploy
        run: >
          docker
          --host ssh://root@shahimatetokruto.ru
          stack deploy
          --compose-file compose.yml
          --detach=false
          --with-registry-auth
          chessbot
